# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Splash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Splash
pod "UnsplasherSDK"
pod 'SDWebImage'
pod 'Lightbox'
pod 'CHTCollectionViewWaterfallLayout/Swift'
pod 'DZNEmptyDataSet'
pod 'JGProgressHUD'
pod 'SVProgressHUD'
pod 'Loaf'
pod 'CollectionViewWaterfallLayout'

end
